-- Table new_clients: TO store new clients' information
CREATE TABLE IF NOT EXISTS new_clients (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
email TEXT NOT NULL,
phone TEXT NOT NULL,
consent BOOL NOT NULL,
timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
)

-- Table existing_clients: TO store existing clients' information
CREATE TABLE IF NOT EXISTS clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    client_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- Table experts: TO store experts' information
CREATE TABLE IF NOT EXISTS experts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    qualification TEXT,
    past_companies TEXT,
    country TEXT,
    areas_of_expertise TEXT,
    years_of_experience INTEGER,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO experts (name, email, qualification, past_companies, country, areas_of_expertise, years_of_experience) VALUES
('Alice Smith', 'alice.smith@example.com', 'PhD, Computer Science', 'Google, Microsoft', 'USA', 'Artificial Intelligence', 15),
('Bob Johnson', 'bob.johnson@example.com', 'MS, Data Science', 'Amazon, Facebook', 'USA', 'Artificial Intelligence', 12),
('Charlie Brown', 'charlie.brown@example.com', 'BS, Computer Engineering', 'IBM', 'Canada', 'Artificial Intelligence', 8),
('Diana Miller', 'diana.miller@example.com', 'PhD, Electrical Engineering', 'Intel, NVIDIA', 'USA', 'Artificial Intelligence', 20),
('Ethan Davis', 'ethan.davis@example.com', 'MS, Statistics', 'Netflix', 'UK', 'Artificial Intelligence', 10),
('Fiona Green', 'fiona.green@example.com', 'PhD, Mathematics', 'DeepMind', 'UK', 'Artificial Intelligence', 18),
('George White', 'george.white@example.com', 'BS, Computer Science', 'Salesforce', 'USA', 'Artificial Intelligence', 7),
('Hannah Black', 'hannah.black@example.com', 'MS, Machine Learning', 'Tesla', 'USA', 'Artificial Intelligence', 11),
('Isaac Grey', 'isaac.grey@example.com', 'PhD, Physics', 'MIT', 'USA', 'Artificial Intelligence', 22),
('Julia Red', 'julia.red@example.com', 'BS, Information Technology', 'Oracle', 'Australia', 'Artificial Intelligence', 9),

('Ken Martinez', 'ken.martinez@example.com', 'PhD, Civil Engineering', 'Bechtel, AECOM', 'USA', 'Civil Engineering', 25),
('Linda Garcia', 'linda.garcia@example.com', 'MS, Structural Engineering', 'Jacobs Engineering', 'USA', 'Civil Engineering', 18),
('Michael Rodriguez', 'michael.rodriguez@example.com', 'BS, Construction Management', 'Skanska', 'Canada', 'Civil Engineering', 12),
('Nancy Williams', 'nancy.williams@example.com', 'PhD, Geotechnical Engineering', 'Golder Associates', 'UK', 'Civil Engineering', 20),
('Oliver Brown', 'oliver.brown@example.com', 'MS, Environmental Engineering', 'CH2M Hill', 'USA', 'Civil Engineering', 15),
('Patricia Davis', 'patricia.davis@example.com', 'BS, Civil Engineering', 'Fluor Corporation', 'Australia', 'Civil Engineering', 10),
('Quentin Wilson', 'quentin.wilson@example.com', 'PhD, Transportation Engineering', 'Parsons Corporation', 'USA', 'Civil Engineering', 22),
('Rachel Garcia', 'rachel.garcia@example.com', 'MS, Water Resources Engineering', 'Stantec', 'Canada', 'Civil Engineering', 14),
('Samuel Martinez', 'samuel.martinez@example.com', 'BS, Civil Engineering', 'Kiewit Corporation', 'USA', 'Civil Engineering', 9),
('Tara Rodriguez', 'tara.rodriguez@example.com', 'PhD, Coastal Engineering', 'Moffatt & Nichol', 'USA', 'Civil Engineering', 21),

('Ursula Clark', 'ursula.clark@example.com', 'MD, Cardiology', 'Mayo Clinic', 'USA', 'Medicine', 20),
('Victor Lewis', 'victor.lewis@example.com', 'MD, Oncology', 'MD Anderson', 'USA', 'Medicine', 22),
('Wendy Young', 'wendy.young@example.com', 'MD, Pediatrics', 'Boston Childrens', 'USA', 'Medicine', 18),
('Xavier Hall', 'xavier.hall@example.com', 'MD, Neurology', 'Johns Hopkins', 'USA', 'Medicine', 25),
('Yvonne Wright', 'yvonne.wright@example.com', 'MD, Surgery', 'Cleveland Clinic', 'USA', 'Medicine', 21),
('Zachary Green', 'zachary.green@example.com', 'MD, Dermatology', 'NYU Langone', 'USA', 'Medicine', 19),
('Amelia King', 'amelia.king@example.com', 'MD, Psychiatry', 'Harvard Medical School', 'USA', 'Medicine', 23),
('Benjamin Adams', 'benjamin.adams@example.com', 'MD, Radiology', 'UCSF Medical Center', 'USA', 'Medicine', 17),
('Charlotte Nelson', 'charlotte.nelson@example.com', 'MD, Anesthesiology', 'Massachusetts General Hospital', 'USA', 'Medicine', 24),
('Daniel Carter', 'daniel.carter@example.com', 'MD, Emergency Medicine', 'Stanford Health Care', 'USA', 'Medicine', 16),

('Emily Parker', 'emily.parker@example.com', 'MBA, Finance', 'Goldman Sachs', 'USA', 'Finance', 15),
('Frank Murphy', 'frank.murphy@example.com', 'MS, Economics', 'JP Morgan Chase', 'USA', 'Finance', 12),
('Grace Bennett', 'grace.bennett@example.com', 'CFA', 'Morgan Stanley', 'USA', 'Finance', 18),
('Henry Wood', 'henry.wood@example.com', 'PhD, Finance', 'Harvard Business School', 'USA', 'Finance', 20),
('Isabella Reed', 'isabella.reed@example.com', 'MBA, Accounting', 'Deloitte', 'USA', 'Finance', 10),
('Jack Coleman', 'jack.coleman@example.com', 'MS, Statistics', 'BlackRock', 'USA', 'Finance', 14),
('Katherine Hayes', 'katherine.hayes@example.com', 'CPA', 'Ernst & Young', 'USA', 'Finance', 16),
('Liam Foster', 'liam.foster@example.com', 'MBA, Investment Banking', 'Citigroup', 'USA', 'Finance', 13),
('Mia Powell', 'mia.powell@example.com', 'MS, Financial Engineering', 'Bloomberg', 'USA', 'Finance', 11),
('Noah Simmons', 'noah.simmons@example.com', 'PhD, Economics', 'Federal Reserve', 'USA', 'Finance', 19),

('Olivia Price', 'olivia.price@example.com', 'JD, Law', 'Skadden Arps', 'USA', 'Law', 10),
('Peter Morgan', 'peter.morgan@example.com', 'LLM, International Law', 'Clifford Chance', 'UK', 'Law', 14),
('Quinn Cooper', 'quinn.cooper@example.com', 'JD, Corporate Law', 'Wachtell Lipton', 'USA', 'Law', 16),
('Riley Hayes', 'riley.hayes@example.com', 'LLM, Tax Law', 'Sullivan & Cromwell', 'USA', 'Law', 12),
('Sophia Bennett', 'sophia.bennett@example.com', 'JD, Criminal Law', 'Public Defender Service', 'USA', 'Law', 8),
('Thomas Wood', 'thomas.wood@example.com', 'LLM, Human Rights Law', 'Amnesty International', 'UK', 'Law', 18),
('Uma Powell', 'uma.powell@example.com', 'JD, Intellectual Property Law', 'Finnegan Henderson', 'USA', 'Law', 13),
('Victor Simmons', 'victor.simmons@example.com', 'LLM, Environmental Law', 'Environmental Defense Fund', 'USA', 'Law', 11),
('Wendy Price', 'wendy.price@example.com', 'JD, Family Law', 'Legal Aid Society', 'USA', 'Law', 9),
('Xavier Morgan', 'xavier.morgan@example.com', 'LLM, Constitutional Law', 'ACLU', 'USA', 'Law', 15),

('Yara Cooper', 'yara.cooper@example.com', 'PhD, Physics', 'CERN', 'Switzerland', 'Physics', 17),
('Zachary Hayes', 'zachary.hayes@example.com', 'MS, Astrophysics', 'NASA', 'USA', 'Physics', 14),
('Aaliyah Bennett', 'aaliyah.bennett@example.com', 'BS, Physics', 'SpaceX', 'USA', 'Physics', 10),
('Benjamin Wood', 'benjamin.wood@example.com', 'PhD, Theoretical Physics', 'Princeton University', 'USA', 'Physics', 20),
('Charlotte Powell', 'charlotte.powell@example.com', 'MS, Nuclear Physics', 'Brookhaven National Laboratory', 'USA', 'Physics', 12),
('Daniel Simmons', 'daniel.simmons@example.com', 'BS, Physics', 'Lockheed Martin', 'USA', 'Physics', 9),
('Emily Price', 'emily.price@example.com', 'PhD, Quantum Physics', 'Caltech', 'USA', 'Physics', 22),
('Frank Morgan', 'frank.morgan@example.com', 'MS, Optics', 'Zeiss', 'Germany', 'Physics', 16),
('Grace Cooper', 'grace.cooper@example.com', 'BS, Physics', 'Boeing', 'USA', 'Physics', 11),
('Henry Hayes', 'henry.hayes@example.com', 'PhD, Condensed Matter Physics', 'MIT', 'USA', 'Physics', 19),

('Isabella Bennett', 'isabella.bennett@example.com', 'PhD, Mechanical Engineering', 'General Electric', 'USA', 'Mechanical Engineering', 18),
('Jack Wood', 'jack.wood@example.com', 'MS, Aerospace Engineering', 'Boeing', 'USA', 'Mechanical Engineering', 15),
('Katherine Powell', 'katherine.powell@example.com', 'BS, Automotive Engineering', 'Tesla', 'USA', 'Mechanical Engineering', 11),
('Liam Simmons', 'liam.simmons@example.com', 'PhD, Robotics', 'Boston Dynamics', 'USA', 'Mechanical Engineering', 21),
('Mia Price', 'mia.price@example.com', 'MS, Thermal Engineering', 'Siemens', 'Germany', 'Mechanical Engineering', 14),
('Noah Morgan', 'noah.morgan@example.com', 'BS, Manufacturing Engineering', 'Ford', 'USA', 'Mechanical Engineering', 10),
('Olivia Cooper', 'olivia.cooper@example.com', 'PhD, Control Systems', 'ABB', 'Switzerland', 'Mechanical Engineering', 19),
('Peter Hayes', 'peter.hayes@example.com', 'MS, Materials Science', 'Alcoa', 'USA', 'Mechanical Engineering', 16),
('Quinn Bennett', 'quinn.bennett@example.com', 'BS, Mechanical Engineering', 'Caterpillar', 'USA', 'Mechanical Engineering', 12),
('Riley Wood', 'riley.wood@example.com', 'PhD, Biomechanics', 'Nike', 'USA', 'Mechanical Engineering', 20),

('Sophia Powell', 'sophia.powell@example.com', 'PhD, Economics', 'World Bank', 'USA', 'Economics', 20),
('Thomas Simmons', 'thomas.simmons@example.com', 'MS, Econometrics', 'IMF', 'USA', 'Economics', 17),
('Uma Price', 'uma.price@example.com', 'BS, Economics', 'Federal Reserve', 'USA', 'Economics', 13),
('Victor Morgan', 'victor.morgan@example.com', 'PhD, Microeconomics', 'University of Chicago', 'USA', 'Economics', 22),
('Wendy Cooper', 'wendy.cooper@example.com', 'MS, Development Economics', 'United Nations', 'USA', 'Economics', 15),
('Xavier Hayes', 'xavier.hayes@example.com', 'BS, Economics', 'Goldman Sachs', 'USA', 'Economics', 11),
('Yara Bennett', 'yara.bennett@example.com', 'PhD, Macroeconomics', 'Harvard University', 'USA', 'Economics', 23),
('Zachary Wood', 'zachary.wood@example.com', 'MS, Labor Economics', 'Department of Labor', 'USA', 'Economics', 19),
('Aaliyah Powell', 'aaliyah.powell@example.com', 'BS, Economics', 'Amazon', 'USA', 'Economics', 10),
('Benjamin Simmons', 'benjamin.simmons@example.com', 'PhD, International Economics', 'Peterson Institute', 'USA', 'Economics', 21),

('Charlotte Price', 'charlotte.price@example.com', 'PhD, Psychology', 'American Psychological Association', 'USA', 'Psychology', 20),
('Daniel Morgan', 'daniel.morgan@example.com', 'MS, Clinical Psychology', 'Mayo Clinic', 'USA', 'Psychology', 17),
('Emily Cooper', 'emily.cooper@example.com', 'BS, Psychology', 'National Institute of Mental Health', 'USA', 'Psychology', 13),
('Frank Hayes', 'frank.hayes@example.com', 'PhD, Cognitive Psychology', 'MIT', 'USA', 'Psychology', 22),
('Grace Bennett', 'grace.bennett@example.com', 'MS, Counseling Psychology', 'Johns Hopkins', 'USA', 'Psychology', 15),
('Henry Wood', 'henry.wood@example.com', 'BS, Psychology', 'Harvard University', 'USA', 'Psychology', 11),
('Isabella Powell', 'isabella.powell@example.com', 'PhD, Social Psychology', 'Stanford University', 'USA', 'Psychology', 23),
('Jack Simmons', 'jack.simmons@example.com', 'MS, Developmental Psychology', 'Yale University', 'USA', 'Psychology', 19),
('Katherine Price', 'katherine.price@example.com', 'BS, Psychology', 'University of California, Los Angeles', 'USA', 'Psychology', 10),
('Liam Morgan', 'liam.morgan@example.com', 'PhD, Neuropsychology', 'Columbia University', 'USA', 'Psychology', 21),

('Mia Cooper', 'mia.cooper@example.com', 'PhD, Computer Science', 'Google', 'USA', 'Software Engineering', 16),
('Noah Hayes', 'noah.hayes@example.com', 'MS, Software Engineering', 'Microsoft', 'USA', 'Software Engineering', 13),
('Olivia Bennett', 'olivia.bennett@example.com', 'BS, Computer Science', 'Amazon', 'USA', 'Software Engineering', 10),
('Peter Wood', 'peter.wood@example.com', 'PhD, Computer Engineering', 'Facebook', 'USA', 'Software Engineering', 20),
('Quinn Powell', 'quinn.powell@example.com', 'MS, Information Technology', 'Apple', 'USA', 'Software Engineering', 14),
('Riley Simmons', 'riley.simmons@example.com', 'BS, Computer Science', 'Netflix', 'USA', 'Software Engineering', 11),
('Sophia Price', 'sophia.price@example.com', 'PhD, Software Engineering', 'IBM', 'USA', 'Software Engineering', 22),
('Thomas Morgan', 'thomas.morgan@example.com', 'MS, Computer Science', 'Salesforce', 'USA', 'Software Engineering', 18),
('Uma Cooper', 'uma.cooper@example.com', 'BS, Software Engineering', 'Twitter', 'USA', 'Software Engineering', 9),
('Victor Hayes', 'victor.hayes@example.com', 'PhD, Computer Science', 'Oracle', 'USA', 'Software Engineering', 19),

('Wendy Bennett', 'wendy.bennett@example.com', 'PhD, Biology', 'Genentech', 'USA', 'Biotechnology', 21),
('Xavier Wood', 'xavier.wood@example.com', 'MS, Biochemistry', 'Pfizer', 'USA', 'Biotechnology', 18),
('Yara Powell', 'yara.powell@example.com', 'BS, Biology', 'Moderna', 'USA', 'Biotechnology', 14),
('Zachary Simmons', 'zachary.simmons@example.com', 'PhD, Microbiology', 'Novartis', 'Switzerland', 'Biotechnology', 23),
('Aaliyah Price', 'aaliyah.price@example.com', 'MS, Genetics', 'Amgen', 'USA', 'Biotechnology', 16),
('Benjamin Morgan', 'benjamin.morgan@example.com', 'BS, Biotechnology', 'Gilead Sciences', 'USA', 'Biotechnology', 12),
('Charlotte Cooper', 'charlotte.cooper@example.com', 'PhD, Immunology', 'Roche', 'Switzerland', 'Biotechnology', 20),
('Daniel Hayes', 'daniel.hayes@example.com', 'MS, Pharmacology', 'Johnson & Johnson', 'USA', 'Biotechnology', 17),
('Emily Bennett', 'emily.bennett@example.com', 'BS, Biology', 'Merck & Co.', 'USA', 'Biotechnology', 13),
('Frank Wood', 'frank.wood@example.com', 'PhD, Bioinformatics', 'Illumina', 'USA', 'Biotechnology', 22);

CREATE TABLE IF NOT EXISTS conversation_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    thread_id TEXT NOT NULL,
    client_id TEXT,
    sender TEXT NOT NULL,
    source TEXT NOT NULL,
    message TEXT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
